# Generated by Django 4.0.10 on 2024-02-08 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='entries',
        ),
        migrations.RemoveField(
            model_name='list',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='List',
        ),
    ]
