# Generated by Django 4.0.10 on 2024-02-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_entry_list_entry_owner_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
