# Generated by Django 4.0.10 on 2023-04-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_artist_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='album',
            constraint=models.UniqueConstraint(fields=('title', 'artist'), name='unique_title_for_artist'),
        ),
    ]
