# Generated by Django 4.0.10 on 2023-04-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_album_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='active_years',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='artist',
            name='origin_country',
            field=models.CharField(default=None, max_length=3),
        ),
    ]
