# Generated by Django 4.0.10 on 2024-02-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_trigram_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ManyToManyField(blank=True, related_name='artists_albums', to='core.artist'),
        ),
    ]
