# Generated by Django 4.0.10 on 2023-04-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_artist_active_years_artist_origin_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='origin_country',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
