# Generated by Django 4.0.10 on 2023-04-13 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_artist_origin_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='active_years',
            new_name='years_active',
        ),
    ]
