# Generated by Django 4.0.10 on 2024-02-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_album_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ManyToManyField(to='core.artist'),
        ),
    ]
