# Generated by Django 4.0.10 on 2024-02-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_album_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='description',
            field=models.CharField(blank=True, max_length=511),
        ),
    ]
