# Generated by Django 4.0.10 on 2024-02-27 17:40

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_genre_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.album_image_file_path),
        ),
    ]
