# Generated by Django 4.0.10 on 2024-02-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_album_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='link',
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ManyToManyField(related_name='albums', to='core.artist'),
        ),
    ]
